---
name: SophiApp 🐛
description: Report errors or unexpected behavior 🤔
body:
  - type: markdown
    attributes:
      value: >
        Make sure you are able to repro it on the latest released version. Please open a [new discussion](https://github.com/Sophia-Community/SophiApp/discussions/new) if you have an idea.
        If you prefer Telegram, you may visit out [chat](https://t.me/sophia_chat). Languages allowed: English & русский.

  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
      - label: Verify that this is not a Windows issue;
      - label: Refer to the [System requirements](https://github.com/Sophia-Community/SophiApp/blob/master/README.md#system-requirements);
      - label: Attach a created log. You may find it in the app folder
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
       1. Go to...
       2. Do this...
       3. Do that...
       4. An error occurs
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear description of what is expected to happen.
    validations:
      required: true
  - type: input
    id: sophiapp-version
    attributes:
      label: SophiApp version
      description: Which version of SophiApp are you using? The version number can be found in the Settings
      placeholder: e.g. 1.0.0.22
    validations:
      required: true
  - type: input
    attributes:
      label: Windows Version
      description: Which version of Windows are you using? Press <kbd>Win</kbd> + <kbd>Pause/Break</kbd> to open the page to copy from.
      placeholder: e.g. Windows 11 21H2 22000.527
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs
      description: |
        Log files to help us to isolate issue.
      placeholder: |
        You can attach image(s) or log file(s) by dragging them into this area.
    validations:
      required: true

  - type: markdown
    attributes:
      value: >
        If SophiApp crashes at the startup, please run this PowerShell code as `admin` [how-to](https://www.howtogeek.com/662611/9-ways-to-open-powershell-in-windows-10/) to find out what caused the program to crash, and attach the table, too.

        ```powershell

        $HashTable = @{
           LogName = "Application"
           Id      = "1000"
        }

        Get-WinEvent -FilterHashtable $HashTable | Where-Object -FilterScript {($_.Level -eq "2") -and ($_.Message -match "SophiApp.exe")} | Select-Object -First 1 | Format-List -Property *


        $HashTable = @{
           LogName = "Application"
           Id      = "1026"
        }

        Get-WinEvent -FilterHashtable $HashTable | Where-Object -FilterScript {($_.Level -eq "2") -and ($_.Message -match "SophiApp.exe")} | Select-Object -First 1 | Format-List -Property *

        ```
