---
name: SophiApp 🐛
description: Report errors or unexpected behavior 🤔
body:
- type: markdown
  attributes:
    value: >
      Make sure you are able to repro it on the latest released version. Please open a [new discussion](https://github.com/Sophia-Community/SophiApp/discussions/new) if you have an idea.
      If you prefer Telegram, you may visit out [chat](https://t.me/sophia_chat). Languages allowed: English & русский.
      
      ```powershell
      $HashTable = @{
         LogName = "Application"
         Id      = "1000"
      }
      Get-WinEvent -FilterHashtable $HashTable | Where-Object -FilterScript {($_.Level -eq "2") -and ($_.Message -match "SophiApp.exe")} | Select-Object -First 1 | Format-List -Property *

      $HashTable = @{
         LogName = "Application"
         Id      = "1026"
      }
      Get-WinEvent -FilterHashtable $HashTable | Where-Object -FilterScript {($_.Level -eq "2") -and ($_.Message -match "SophiApp.exe")} | Select-Object -First 1 | Format-List -Property *
      ```
- type: checkboxes
  attributes:
    label: Prerequisites
    options:
    - label: Verify that this is not a Windows issue;
    - label: Refer to the [System requirements](https://github.com/Sophia-Community/SophiApp/blob/master/README.md#system-requirements);
    - label: Attach a created log. You may find it in the app folder
- type: textarea
  attributes:
    label: Steps to reproduce
    description: >
      Write something :)
  validations:
    required: true
