name: Build

on: push

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        platform: [Any CPU]

    runs-on: windows-latest

    env:
      App_Name: SophiApp
      App_Zip: SophiApp.zip      
      App_Project_Path: SophiApp\SophiApp.sln
      App_Release_Path: SophiApp\SophiApp\bin\Release

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Setup Windows 10 Sdk
      uses: GuillaumeFalourd/setup-windows10-sdk-action@v1
      with:
        sdk-version: 19041
        
    - name: Find winmd
      run: |
        Get-ChildItem -Path "C:\Program Files\" -Recurse -Force -ErrorAction SilentlyContinue | ft -AutoSize
        Get-ChildItem -Path "C:\Program Files (x86)\" -Recurse -Force -ErrorAction SilentlyContinue | ft -AutoSize
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1          
    
    - name: Run MSBuild
      run: msbuild $env:App_Project_Path /p:Configuration=$env:Configuration /p:platform=$env:Platform
      env:
        Platform: ${{ matrix.platform }}        
        Configuration: ${{ matrix.configuration }}

    - name: Cleanup
      run: |
        Get-ChildItem -Path $env:App_Release_Path -Exclude "*.exe" | Remove-Item -Force -Confirm:$false
        Copy-Item -Path README.md -Destination $env:App_Release_Path -Confirm:$false -Force
    
    - name: Compress
      run: |
        $Build_Directory = Rename-Item -Path $env:App_Release_Path -NewName $env:App_Name -PassThru | Select-Object -ExpandProperty FullName          
        Compress-Archive -Path $Build_Directory -DestinationPath $env:App_Zip -Verbose

    - name: Release
      uses: svenstaro/upload-release-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: SophiApp.zip
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
        prerelease: true
