name: App Build

on: [push]
 
jobs:
  build:
    runs-on: windows-latest

    steps:    
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build with MSBuild
      run: msbuild  SophiApp.sln -p:Configuration=Release
