on: [push]
 
jobs:
  build:
    runs-on: windows-latest

    steps:    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.0
    - name: Build with MSBuild
      run: msbuild SophiApp\SophiApp.sln -p:Configuration=Release
